model:
  type: random_forest
  parameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42

data:
  path: data/heart_attack_data.csv
  test_size: 0.2
  random_state: 42

features:
  - age
  - sex
  - cp
  - trestbps
  - chol
  - fbs
  - restecg
  - thalach
  - exang
  - oldpeak
  - slope
  - ca
  - thal

target: target_column_name